- [request, req]
- [response, res]
- [parameter, param]
- [temporary, temp]
- [source, src]
- [result, res]
- [return, rtn]
- [database, db]
- [administrator, adm]
- [password, pwd]
- [user, usr]
- [transaction, trx]
- [server, srv]
- [service, svc]
- [select, sel]
- [modify, mod]
- [query, qry]
- [array, arr]
- [timestamp, ts]
- [length, len]
- [positive, pos]
- [negative, neg]
- [image, img]
- [number, num]
- [text, txt]
- [dictionary, dict]
- [stack, stk]
- [segment, seg]
- [sequence, seq]
- [character, char]
- [string, str]
- [bitmap, bmp]
- [container, cntr]
- [status, stat]
- [configuration, config]
- [function, func]
- [object, obj]
- [argument, arg]
- [variable, v]
- [sort, of]
- [aidevops, ai]
- [calculate, calc]
- [addition, add]
- [subtraction, sub]
- [multiplication, mul]
- [division, div]
- [hexadecimal, hex]
- [statistic, stat]
- [summation, sum]
- [average, avg]
- [maximum, max]
- [minimum, min]
- [middle, mid]
- [increment, inc]
- [increase, inc]
- [decrease, dec]
- [different, diff]
- [frequency, freq]
- [optimization, opt]
- [total, tot]
- [vertical, vert]
- [horizontal, horz]
- [column, col]
- [positon, pos]
- [point, pt]
- [pointer, ptr]
- [index, idx]
- [value, val]
- [reference, ref]
- [original, orig]
- [address, addr]
- [coordinates, coord]
- [previous, pre]
- [current, cur]
- [initalize, init]
- [destination, dst]
- [iteration, itr]
- [count, cnt]
- [resource, res]
- [result, res]
- [return, rtn]
- [answer, ans]
- [buffer, buf]
- [database, db]
- [administrator, adm]
- [password, pwd]
- [user, usr]
- [directory, dir]
- [document, doc]
- [library, lib]
- [function, func]
- [object, obj]
- [argument, arg]
- [instance, ins]
- [variable, v]
- [parameter, param]
- [encode, enc]
- [print, prn]
- [delete, del]
- [insert, ins]
- [error, err]
- [break, brk]
- [package, pkg]
- [escape, esc]
- [execute, exec]
- [command, cmd]
- [configuration, config]
- [edit, edt]
- [display, disp]
- [initialize, init]
- [trigger, trig]
- [capture, capcapt]
- [system, sys]
- [environment, env]
- [window, win]
- [device, dev]
- [message, msg]
- [signal, sig]
- [information, info]
- [accumulator, acc]
- [address, addr]
- [action, act]
- [active, act]
- [amplitude, amp]
- [analog, input]
- [analog, i/o]
- [alarm, alm]
- [allocate, alloc]
- [analog, output]
- [apparent, app]
- [argument, arg]
- [assemble, asm]
- [attribute, attrib]
- [block, blk]
- [buffer, buf]
- [button, btn]
- [calibration, cal]
- [calculate, calc]
- [configuration, cfg]
- [channel, ch]
- [change, chg]
- [check, chk]
- [clock, clk]
- [clear, clr]
- [command, cmd]
- [compare, cmp]
- [complete, comp]
- [count, cnt]
- [counter, ctr]
- [column, col]
- [communication, comm]
- [connect, con]
- [construct, cons]
- [control, ctrl]
- [context, ctx]
- [convert, conv]
- [copy, cp]
- [current, cur]
- [cursor, csr]
- [decrease, dec]
- [decimal, dec]
- [define, def]
- [degree, deg]
- [delete, del]
- [destination, dst]
- [descriptor, desc]
- [device, dev]
- [discrete, input]
- [digit, dig]
- [discrete, i/o]
- [discrete, output]
- [disable, dis]
- [display, disp]
- [discovery, disc]
- [division, div]
- [delay, dly]
- [dynamic, dyn]
- [effective, eff]
- [electric, elec]
- [enable, en]
- [engine, eng]
- [equivalent, equiv]
- [error, err]
- [ethernet, eth]
- [extension, ext]
- [exception, exc]
- [expiration, exp]
- [exponent, exp]
- [field, fld]
- [function, fnct]
- [fraction, fract]
- [frequency, freq]
- [generate, gen]
- [harmonic, harm]
- [hexadecimal, hex]
- [high, hi]
- [history, hist]
- [high, priority]
- [hour, hr]
- [impulse, imp]
- [input, in]
- [initialization, init]
- [initialize, init]
- [instruction, instr]
- [interrupt, int]
- [invert, inv]
- [index, ix]
- [keyboard, key]
- [length, len]
- [limit, lim]
- [low, lo]
- [lower, le]
- [lowest, lo]
- [magnitude, mag]
- [mantissa, man]
- [manual, man]
- [manufacture, mfg]
- [maximum, max]
- [mailbox, mbox]
- [minimum, min]
- [move, mov]
- [message, msg]
- [measure, meas]
- [mask, msk]
- [multiplication, mul]
- [multiplex, mux]
- [make, mk]
- [negative, neg]
- [number, num]
- [neutral, neut]
- [operation, os]
- [optimize, opt]
- [original, orig]
- [output, out]
- [overflow, ovf]
- [package, pkg]
- [parameter, param]
- [performance, perf]
- [period, per]
- [phase, ph]
- [position, pos]
- [positive, pos]
- [power, pwr]
- [previous, prev]
- [priority, prio]
- [printer, prt]
- [process, proc]
- [product, prod]
- [protocol, prot]
- [pointer, ptr]
- [queue, q]
- [quality, qlty]
- [reactive, react]
- [recall, rcl]
- [rectangle, rect]
- [read, rd]
- [ready, rdy]
- [reference, ref]
- [register, reg]
- [request, req]
- [reserve, resv]
- [response, resp]
- [return, rtn]
- [reverse, revs]
- [repeat, rpt]
- [real, time]
- [receive, rx]
- [sample, smp]
- [schedule, sched]
- [scheduler, sched]
- [screen, scr]
- [second, sec]
- [segment, seg]
- [select, sel]
- [semaphore, sem]
- [sequence, seq]
- [server, svr]
- [signal, sig]
- [sourse, src]
- [statistic, stat]
- [status, stat]
- [stack, stk]
- [standard, std]
- [string, str]
- [subtraction, sub]
- [switch, sw]
- [synchronize, synch]
- [system, syst]
- [table, tbl]
- [threshold, th]
- [timer, tmr]
- [toggle, tgl]
- [total, tot]
- [trigger, trig]
- [time, stamp]
- [timeout, to]
- [utility, util]
- [value, val]
- [vector, vect]
- [version, ver]
- [variable, v]
- [visible, vis]
- [voltage, vol]
- [watchdog, wdog]
- [write, wr]
- [deduplicate, dedup]

